name: calorie_tracker_app_pro
description: A comprehensive calorie tracking mobile app with AI food recognition.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core dependencies
  cupertino_icons: ^1.0.2
  
  # State management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Charts and visualization  
  fl_chart: ^0.64.0
  
  # Image handling
  image_picker: ^1.0.4
  image: ^4.1.3
  
  # Internationalization
  intl: ^0.18.1
  
  # Calendar
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true